proxy:
  #  代理配置
  #  国内墙了gpt的api，所以得用代理，一般你使用的代理软件会有相关信息，例子：
  #  host: 127.0.0.1
  #  port: 7890
  #  若不需要留空即可
  host: 127.0.0.1
  port: 50643

account:
  #qq
  qq: 123456
  password: xxxx

  #ChatGPT
  apiKey:
   - sk-xxxx
   - sk-xxxx
  #ChatGPT 4
  apiKeyPlus:
    - sk-xxxx
    - sk-xxxx
spring:
  redis:
    host: 127.0.0.1
    port: 6378
    password: 123456
    database: 0